name: bfd9000
services:
  bfd9000:
    image: ghcr.io/open-ortho/edu.case.bfd9000:local
    container_name: bfd9000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    # command: python manage.py runserver 0.0.0.0:9000
    env_file:
      - .env
    volumes:
      # Keep media files (uploads) persistent
      - media_volume:/app/media
      # Mount local SQLite database for persistence
      - ./db.sqlite3:/app/db.sqlite3
    # environment:
    #   - DEBUG=1
    #   - SECRET_KEY=dev_secret_key
    #   - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],0.0.0.0

volumes:
  media_volume:
