# Generated by Django 5.2.7 on 2025-10-12 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use', models.CharField(blank=True, max_length=16)),
                ('type', models.CharField(blank=True, max_length=16)),
                ('line1', models.CharField(blank=True, max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('district', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['country', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.URLField(help_text='Code system URL', max_length=255)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=128)),
                ('display', models.CharField(blank=True, max_length=255)),
                ('meaning', models.TextField(blank=True, help_text='Extended description')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['system', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_name', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('curator', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, help_text='Collection start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Collection end date', null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.address')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_period_start', models.DateField(blank=True, help_text='Encounter start date', null=True)),
                ('actual_period_end', models.DateField(blank=True, help_text='Encounter end date', null=True)),
                ('procedure_occurrence_age', models.DurationField(blank=True, null=True)),
                ('procedure_occurrence_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_diagnosis', to='archive.coding')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('procedure_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters_procedure', to='archive.coding')),
            ],
            options={
                'ordering': ['-actual_period_start'],
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use', models.CharField(choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temporary'), ('secondary', 'Secondary'), ('old', 'Old')], default='official', max_length=16)),
                ('system', models.URLField(help_text='Identifier system URL', max_length=255)),
                ('value', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['system', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.address')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_datetime', models.DateTimeField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('endpoint', models.URLField(blank=True, help_text='URL endpoint for imaging data', max_length=500)),
                ('instance_uid', models.CharField(blank=True, help_text='DICOM Instance UID', max_length=64)),
                ('instance_sop_class', models.CharField(blank=True, help_text='DICOM SOP Class', max_length=64)),
                ('instance_number', models.PositiveIntegerField(blank=True, null=True)),
                ('series_uid', models.CharField(blank=True, help_text='DICOM Series UID', max_length=64)),
                ('body_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_studies_body_site', to='archive.coding')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.collection')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_studies', to='archive.encounter')),
                ('identifiers', models.ManyToManyField(blank=True, related_name='imaging_studies', to='archive.identifier')),
                ('laterality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_studies_laterality', to='archive.coding')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_studies_record_type', to='archive.coding')),
                ('scan_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_studies', to=settings.AUTH_USER_MODEL)),
                ('series_modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_studies_series_modality', to='archive.coding')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_studies_view', to='archive.coding')),
                ('scan_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.location')),
            ],
            options={
                'verbose_name_plural': 'Imaging Studies',
                'ordering': ['-scan_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('physical_location_box', models.CharField(blank=True, max_length=128)),
                ('physical_location_shelf', models.CharField(blank=True, max_length=128)),
                ('physical_location_tray', models.CharField(blank=True, max_length=128)),
                ('physical_location_compartment', models.CharField(blank=True, max_length=128)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.collection')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='archive.encounter')),
                ('identifiers', models.ManyToManyField(blank=True, related_name='records', to='archive.identifier')),
                ('imaging_study', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='archive.imagingstudy')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('physical_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_physical_location', to='archive.address')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_record_type', to='archive.coding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=16)),
                ('birth_date', models.DateField()),
                ('humanname_family', models.CharField(help_text='Family name', max_length=128)),
                ('humanname_given', models.CharField(help_text='Given name', max_length=128)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.address')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects_ethnicity', to='archive.coding')),
                ('identifiers', models.ManyToManyField(blank=True, related_name='subjects', to='archive.identifier')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('palatal_cleft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects_palatal_cleft', to='archive.coding')),
                ('skeletal_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects_skeletal_pattern', to='archive.coding')),
            ],
            options={
                'ordering': ['humanname_family', 'humanname_given'],
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='archive.subject'),
        ),
        migrations.AddIndex(
            model_name='coding',
            index=models.Index(fields=['system', 'code'], name='archive_cod_system_409408_idx'),
        ),
        migrations.AddConstraint(
            model_name='coding',
            constraint=models.UniqueConstraint(fields=('system', 'version', 'code'), name='unique_coding_system_version_code'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['short_name'], name='archive_col_short_n_e6a50d_idx'),
        ),
        migrations.AddIndex(
            model_name='identifier',
            index=models.Index(fields=['system', 'value'], name='archive_ide_system_b084a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='identifier',
            constraint=models.UniqueConstraint(fields=('system', 'value'), name='unique_identifier_system_value'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['encounter'], name='archive_ima_encount_87a220_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['series_uid'], name='archive_ima_series__2bbc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['instance_uid'], name='archive_ima_instanc_fd5557_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['scan_datetime'], name='archive_ima_scan_da_562d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['encounter'], name='archive_rec_encount_544328_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['birth_date'], name='archive_sub_birth_d_27a084_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['humanname_family', 'humanname_given'], name='archive_sub_humanna_b4f190_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['subject', 'actual_period_start'], name='archive_enc_subject_8b72f2_idx'),
        ),
    ]
