# Generated by Django 4.2.25 on 2026-02-28 05:57

import archive.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use', models.CharField(blank=True, max_length=16)),
                ('type', models.CharField(blank=True, max_length=16)),
                ('line1', models.CharField(blank=True, max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('district', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['country', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.URLField(help_text='Code system URL', max_length=255)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=128)),
                ('display', models.CharField(blank=True, max_length=255)),
                ('meaning', models.TextField(blank=True, help_text='Extended description')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['system', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_name', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('curator', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, help_text='Collection start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Collection end date', null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.address')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_period_start', models.DateField(blank=True, help_text='Encounter start date', null=True)),
                ('actual_period_start_raw', models.CharField(blank=True, help_text='Original encounter date token from import sources', max_length=64)),
                ('actual_period_start_precision', models.CharField(blank=True, choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year'), ('unknown', 'Unknown')], help_text='Precision of actual_period_start', max_length=16)),
                ('actual_period_start_uncertain', models.BooleanField(default=False, help_text='True when actual_period_start is inferred from partial data')),
                ('actual_period_end', models.DateField(blank=True, help_text='Encounter end date', null=True)),
                ('procedure_occurrence_age', models.DurationField(blank=True, null=True)),
                ('procedure_occurrence_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_diagnosis', to='archive.coding')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('procedure_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters_procedure', to='archive.coding')),
            ],
            options={
                'ordering': ['-actual_period_start'],
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use', models.CharField(choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temporary'), ('secondary', 'Secondary'), ('old', 'Old')], default='official', max_length=16)),
                ('system', models.URLField(help_text='Identifier system URL', max_length=255)),
                ('value', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['system', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_uid', models.CharField(blank=True, help_text='DICOM Study Instance UID', max_length=64)),
                ('endpoint', models.URLField(blank=True, help_text='URL providing access to study-level data (DICOMweb, PACS, etc.)', max_length=500)),
                ('description', models.CharField(blank=True, help_text='Institution-generated human readable description of the study', max_length=255)),
                ('collection', models.ForeignKey(help_text='Dataset/collection this study belongs to', on_delete=django.db.models.deletion.PROTECT, to='archive.collection')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(help_text='The Encounter this ImagingStudy documents (one study per encounter)', on_delete=django.db.models.deletion.PROTECT, related_name='imaging_study', to='archive.encounter')),
                ('identifiers', models.ManyToManyField(blank=True, related_name='imaging_studies', to='archive.identifier')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Imaging Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.address')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ValueSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('url', models.URLField(help_text='Canonical URL', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('publication_url', models.URLField(blank=True, max_length=255)),
                ('code_system_url', models.URLField(blank=True, max_length=255)),
                ('code_system_publication_url', models.URLField(blank=True, max_length=255)),
                ('code_system_status', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ValueSetConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.coding')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('valueset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.valueset')),
            ],
        ),
        migrations.AddField(
            model_name='valueset',
            name='codings',
            field=models.ManyToManyField(blank=True, related_name='value_sets', through='archive.ValueSetConcept', to='archive.coding'),
        ),
        migrations.AddField(
            model_name='valueset',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valueset',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=16)),
                ('birth_date', models.DateField()),
                ('humanname_family', models.CharField(blank=True, help_text='Family name', max_length=128, null=True)),
                ('humanname_given', models.CharField(blank=True, help_text='Given name', max_length=128, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.address')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='archive.collection')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects_ethnicity', to='archive.coding')),
                ('identifiers', models.ManyToManyField(blank=True, related_name='subjects', to='archive.identifier')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('palatal_cleft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects_palatal_cleft', to='archive.coding')),
                ('skeletal_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects_skeletal_pattern', to='archive.coding')),
            ],
            options={
                'ordering': ['humanname_family', 'humanname_given'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(blank=True, help_text='DICOM Series Instance UID', max_length=64)),
                ('description', models.CharField(blank=True, help_text='Short human-readable description of this series', max_length=255)),
                ('acquisition_location', models.ForeignKey(blank=True, help_text='Physical or institutional location where this series was acquired/digitized', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_acquisition_location', to='archive.location')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('imaging_study', models.ForeignKey(help_text='The ImagingStudy this series belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='series', to='archive.imagingstudy')),
                ('modality', models.ForeignKey(blank=True, help_text='DICOM modality code for this series (e.g. RG, XC, M3D)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_modality', to='archive.coding')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('record_type', models.ForeignKey(help_text='SNOMED CT code identifying the clinical study type (e.g. Cephalogram, Dental model)', on_delete=django.db.models.deletion.PROTECT, related_name='series_record_type', to='archive.coding')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['imaging_study', 'record_type'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sop_instance_uid', models.CharField(blank=True, help_text='DICOM SOP Instance UID uniquely identifying this artifact instance', max_length=64)),
                ('acquisition_datetime', models.DateTimeField(blank=True, help_text='Date and time this artifact was acquired or scanned', null=True)),
                ('source_file', models.FileField(blank=True, help_text='Raw uploaded file (PNG/TIFF/STL). Transient — may be deleted after archival.', null=True, upload_to=archive.models.record_upload_path)),
                ('thumbnail', models.ImageField(blank=True, help_text='Compressed preview image (<300KB JPEG).', null=True, upload_to=archive.models.record_thumbnail_path)),
                ('endpoint', models.URLField(blank=True, help_text='URL of the permanently archived virtual record (DICOMweb, Box, PACS, etc.)', max_length=500)),
                ('patient_orientation', models.CharField(blank=True, help_text='DICOM PatientOrientation (0020,0020), encoded as A\\F', max_length=16)),
                ('image_transform_ops', models.JSONField(blank=True, default=list, help_text='Ordered list of transform ops applied to preview image')),
                ('physical_location_box', models.CharField(blank=True, help_text='Box identifier in physical archive', max_length=128)),
                ('physical_location_shelf', models.CharField(blank=True, help_text='Shelf identifier in physical archive', max_length=128)),
                ('physical_location_tray', models.CharField(blank=True, help_text='Tray identifier in physical archive', max_length=128)),
                ('physical_location_compartment', models.CharField(blank=True, help_text='Compartment identifier in physical archive', max_length=128)),
                ('device', models.CharField(blank=True, help_text='Device used to capture this record', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('identifiers', models.ManyToManyField(blank=True, related_name='records', to='archive.identifier')),
                ('image_type', models.ForeignKey(blank=True, help_text='Legacy Bolton/Lancaster compound code encoding medium+view (e.g. L, SM). See docs/data_model.md.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_image_type', to='archive.coding')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('physical_location', models.ForeignKey(blank=True, help_text='Physical location where physical artifact is stored (archive address)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_physical_location', to='archive.address')),
                ('scan_operator', models.ForeignKey(blank=True, help_text='User who performed the scan or acquisition of this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_scanned', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(help_text='The Series this record instance belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='records', to='archive.series')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='archive.subject'),
        ),
        migrations.AddIndex(
            model_name='valuesetconcept',
            index=models.Index(fields=['valueset', 'coding'], name='archive_val_valuese_ac2edd_idx'),
        ),
        migrations.AddConstraint(
            model_name='valuesetconcept',
            constraint=models.UniqueConstraint(fields=('valueset', 'coding'), name='unique_valueset_coding'),
        ),
        migrations.AddIndex(
            model_name='valueset',
            index=models.Index(fields=['slug'], name='archive_val_slug_6f75bc_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['birth_date'], name='archive_sub_birth_d_27a084_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['humanname_family', 'humanname_given'], name='archive_sub_humanna_b4f190_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['imaging_study'], name='archive_ser_imaging_9a7561_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['series'], name='archive_rec_series__53598a_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['encounter'], name='archive_ima_encount_87a220_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['instance_uid'], name='archive_ima_instanc_fd5557_idx'),
        ),
        migrations.AddIndex(
            model_name='identifier',
            index=models.Index(fields=['system', 'value'], name='archive_ide_system_b084a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='identifier',
            constraint=models.UniqueConstraint(fields=('system', 'value'), name='unique_identifier_system_value'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['subject', 'actual_period_start'], name='archive_enc_subject_8b72f2_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['short_name'], name='archive_col_short_n_e6a50d_idx'),
        ),
        migrations.AddIndex(
            model_name='coding',
            index=models.Index(fields=['system', 'code'], name='archive_cod_system_409408_idx'),
        ),
        migrations.AddConstraint(
            model_name='coding',
            constraint=models.UniqueConstraint(fields=('system', 'version', 'code'), name='unique_coding_system_version_code'),
        ),
    ]
