# Generated by Django 5.2.8 on 2025-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingstudy',
            name='source_file',
            field=models.FileField(blank=True, help_text='Original uploaded file (PNG/STL)', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
