# Generated by Django 5.2.8 on 2025-12-02 20:03

from django.db import migrations

def init_codings(apps, schema_editor):
    # Import constants at function scope to keep the migration module
    # importable without depending on application code at module level.
    from archive.constants import (
        SYSTEM_RECORD_TYPE, SYSTEM_ORIENTATION, SYSTEM_MODALITY, 
        SYSTEM_PROCEDURE, SYSTEM_BODY_SITE
    )

    Coding = apps.get_model('archive', 'Coding')

    # Record Types (Procedures/Objects)
    # Mapped from CSV and standard SNOMED codes
    record_types = [
        ('201456002', 'Cephalogram'),
        ('268425006', 'Pelvis X-ray'),
        ('39714003', 'Skeletal X-ray of wrist and hand'),
        ('1597004', 'Skeletal X-ray of ankle and foot'),
        ('302189007', 'Dental model'), # Added for plaster_model
    ]
    for code, display in record_types:
        Coding.objects.get_or_create(
            system=SYSTEM_RECORD_TYPE,
            code=code,
            defaults={'display': display}
        )

    # Orientations (Projections & Laterality)
    orientations = [
        # Projections
        ('399198007', 'Right lateral projection'),
        ('399173006', 'Left lateral projection'),
        ('272479007', 'Posteroanterior projection'),
        ('399348003', 'Antero-posterior projection'),
        # Laterality
        ('7771000', 'Left'),
        ('24028007', 'Right'),
        # DICOM Orientations (mapped to SNOMED or kept as DICOM if needed, 
        # but sticking to SNOMED for consistency in this system as per CSV mix)
    ]
    for code, display in orientations:
        Coding.objects.get_or_create(
            system=SYSTEM_ORIENTATION,
            code=code,
            defaults={'display': display}
        )

    # Modalities (DICOM)
    modalities = [
        ('RG', 'Radiographic Imaging'),
        ('SI', 'Scanned Image'),
        ('XC', 'External-camera Photography'), # Standard DICOM
        ('M3D', 'Model for 3D Manufacturing'), # Standard DICOM for STL
    ]
    for code, display in modalities:
        Coding.objects.get_or_create(
            system=SYSTEM_MODALITY,
            code=code,
            defaults={'display': display}
        )

    # Body Sites (SNOMED)
    body_sites = [
        ('69536005', 'Head'), # Standard SNOMED for Head
        ('609617007', 'Structure of pelvic segment of trunk'),
        ('731298009', 'Entire ankle and foot'),
        ('729875002', 'Entire wrist and hand'),
        ('1927002', 'Entire left elbow region'),
        ('71889004', 'Entire right elbow region'),
        ('210659002', 'Entire left knee'),
        ('210562007', 'Entire right knee'),
    ]
    for code, display in body_sites:
        Coding.objects.get_or_create(
            system=SYSTEM_BODY_SITE,
            code=code,
            defaults={'display': display}
        )

    # Procedures
    # Currently no generic procedures in the spreadsheet
    procedures = []
    for code, display in procedures:
        Coding.objects.get_or_create(
            system=SYSTEM_PROCEDURE,
            code=code,
            defaults={'display': display}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_imagingstudy_source_file'),
    ]

    operations = [
        migrations.RunPython(init_codings),
    ]
