# Generated by Django 5.2.12 on 2026-03-04 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_seed_codings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('identifier__gt', '')), fields=('identifier', 'model_number'), name='unique_device_identifier_model'),
        ),
    ]
