# Generated by Django 4.2.25 on 2026-02-28 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_seed_codings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='City or locality', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, help_text='District or county', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(blank=True, help_text='Primary street address line', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, help_text='Secondary street address line', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal or ZIP code', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, help_text='State, province, or region', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, help_text='Address type (postal, physical, both)', max_length=16),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='address',
            name='use',
            field=models.CharField(blank=True, help_text='Address use (home, work, temp, etc.)', max_length=16),
        ),
        migrations.AlterField(
            model_name='coding',
            name='code',
            field=models.CharField(help_text='Code value in the code system', max_length=128),
        ),
        migrations.AlterField(
            model_name='coding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='coding',
            name='display',
            field=models.CharField(blank=True, help_text='Human-readable label for this code', max_length=255),
        ),
        migrations.AlterField(
            model_name='coding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='coding',
            name='version',
            field=models.CharField(blank=True, help_text='Code system version', max_length=64),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='curator',
            field=models.CharField(blank=True, help_text='Primary curator or maintainer of the collection', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, help_text='Narrative description of collection scope'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='full_name',
            field=models.CharField(help_text='Human-readable collection name', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='institution',
            field=models.CharField(blank=True, help_text='Institution responsible for the collection', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='short_name',
            field=models.CharField(help_text='Short unique collection key used in paths and filters', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='diagnosis',
            field=models.ForeignKey(blank=True, help_text='Optional diagnostic coding associated with this encounter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_diagnosis', to='archive.coding'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='procedure_code',
            field=models.ForeignKey(help_text='Procedure coding describing the encounter type', on_delete=django.db.models.deletion.PROTECT, related_name='encounters_procedure', to='archive.coding'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='procedure_occurrence_age',
            field=models.DurationField(blank=True, help_text='Age at procedure/encounter when supplied by source data', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='procedure_occurrence_datetime',
            field=models.DateTimeField(blank=True, help_text='Exact procedure occurrence datetime when known', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='subject',
            field=models.ForeignKey(help_text='Subject linked to this encounter', on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='archive.subject'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='use',
            field=models.CharField(choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temporary'), ('secondary', 'Secondary'), ('old', 'Old')], default='official', help_text='FHIR Identifier.use semantics', max_length=16),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='value',
            field=models.CharField(help_text='Identifier value in the given system', max_length=128),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='identifiers',
            field=models.ManyToManyField(blank=True, help_text='External identifiers for this imaging study', related_name='imaging_studies', to='archive.identifier'),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Postal address for this location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Name of facility or location', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='record',
            name='identifiers',
            field=models.ManyToManyField(blank=True, help_text='External identifiers for this record instance', related_name='records', to='archive.identifier'),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='series',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='series',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='birth_date',
            field=models.DateField(help_text='Subject date of birth'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], help_text='Administrative sex/gender for the subject', max_length=16),
        ),
        migrations.AlterField(
            model_name='subject',
            name='identifiers',
            field=models.ManyToManyField(blank=True, help_text='External identifiers associated with this subject', related_name='subjects', to='archive.identifier'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='code_system_publication_url',
            field=models.URLField(blank=True, help_text='Documentation URL for the code system', max_length=255),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='code_system_status',
            field=models.CharField(blank=True, help_text='Status of the underlying code system', max_length=32),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='code_system_url',
            field=models.URLField(blank=True, help_text='Canonical URL for the related code system', max_length=255),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='codings',
            field=models.ManyToManyField(blank=True, help_text='Codes included in this ValueSet via ValueSetConcept links', related_name='value_sets', through='archive.ValueSetConcept', to='archive.coding'),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='description',
            field=models.TextField(blank=True, help_text='Narrative description of this ValueSet'),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='name',
            field=models.CharField(help_text='Computable ValueSet name', max_length=255),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='publication_url',
            field=models.URLField(blank=True, help_text='Documentation URL for this ValueSet', max_length=255),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='publisher',
            field=models.CharField(blank=True, help_text='Organization that publishes this ValueSet', max_length=255),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='slug',
            field=models.SlugField(help_text='Internal stable key used by API queries', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='status',
            field=models.CharField(blank=True, help_text='Publication status (e.g., active, draft)', max_length=32),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='title',
            field=models.CharField(blank=True, help_text='Human-readable ValueSet title', max_length=255),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
        migrations.AlterField(
            model_name='valueset',
            name='version',
            field=models.CharField(blank=True, help_text='Version string for this ValueSet', max_length=64),
        ),
        migrations.AlterField(
            model_name='valuesetconcept',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created'),
        ),
        migrations.AlterField(
            model_name='valuesetconcept',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated'),
        ),
    ]
