# Generated by Django 4.2.25 on 2026-02-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_address_city_alter_address_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Primary address associated with this collection', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.address'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Subject mailing or residence address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.address'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection/dataset the subject belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='archive.collection'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='ethnicity',
            field=models.ForeignKey(blank=True, help_text='Optional ethnicity coding for subject demographics', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects_ethnicity', to='archive.coding'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='palatal_cleft',
            field=models.ForeignKey(blank=True, help_text='Optional palatal cleft coding', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects_palatal_cleft', to='archive.coding'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='skeletal_pattern',
            field=models.ForeignKey(blank=True, help_text='Optional skeletal pattern coding', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects_skeletal_pattern', to='archive.coding'),
        ),
        migrations.AlterField(
            model_name='valuesetconcept',
            name='coding',
            field=models.ForeignKey(help_text='Coding member included in the ValueSet', on_delete=django.db.models.deletion.CASCADE, to='archive.coding'),
        ),
        migrations.AlterField(
            model_name='valuesetconcept',
            name='valueset',
            field=models.ForeignKey(help_text='ValueSet that includes the coding', on_delete=django.db.models.deletion.CASCADE, to='archive.valueset'),
        ),
    ]
