# Generated by Django 4.2.25 on 2026-01-27 22:58
# modified to verify migration 0003 (see review comments on #28)

import archive.models
from django.db import migrations, models

def init_codings(apps, schema_editor):
    Coding = apps.get_model('archive', 'Coding')

    # Define systems locally to avoid importing app modules at migration import time
    SYSTEM_RECORD_TYPE = 'http://snomed.info/sct'
    SYSTEM_ORIENTATION = 'http://snomed.info/sct'
    SYSTEM_MODALITY = 'http://dicom.nema.org/resources/ontology/DCM'
    SYSTEM_PROCEDURE = 'http://snomed.info/sct'
    SYSTEM_BODY_SITE = 'http://snomed.info/sct'

    # Helper that uses update_or_create to ensure display is set/updated
    def ensure(system, code, display):
        Coding.objects.update_or_create(
            system=system,
            code=code,
            defaults={'display': display}
        )

    # Record Types
    record_types = [
        ('201456002', 'Cephalogram'),
        ('268425006', 'Pelvis X-ray'),
        ('39714003', 'Skeletal X-ray of wrist and hand'),
        ('1597004', 'Skeletal X-ray of ankle and foot'),
        ('302189007', 'Dental model'),
    ]
    for code, display in record_types:
        ensure(SYSTEM_RECORD_TYPE, code, display)

    # Orientations (projections & laterality)
    orientations = [
        ('399198007', 'Right lateral projection'),
        ('399173006', 'Left lateral projection'),
        ('272479007', 'Posteroanterior projection'),
        ('399348003', 'Antero-posterior projection'),
        ('7771000', 'Left'),
        ('24028007', 'Right'),
    ]
    for code, display in orientations:
        ensure(SYSTEM_ORIENTATION, code, display)

    # Modalities (DICOM)
    modalities = [
        ('RG', 'Radiographic Imaging'),
        ('SI', 'Scanned Image'),
        ('XC', 'External-camera Photography'),
        ('M3D', 'Model for 3D Manufacturing'),
    ]
    for code, display in modalities:
        ensure(SYSTEM_MODALITY, code, display)

    # Body Sites (SNOMED)
    body_sites = [
        ('69536005', 'Head'),
        ('609617007', 'Structure of pelvic segment of trunk'),
        ('731298009', 'Entire ankle and foot'),
        ('729875002', 'Entire wrist and hand'),
        ('1927002', 'Entire left elbow region'),
        ('71889004', 'Entire right elbow region'),
        ('210659002', 'Entire left knee'),
        ('210562007', 'Entire right knee'),
    ]
    for code, display in body_sites:
        ensure(SYSTEM_BODY_SITE, code, display)

    # Procedures (currently empty placeholder)
    procedures = []
    for code, display in procedures:
        ensure(SYSTEM_PROCEDURE, code, display)

def remove_codings(apps, schema_editor):
    Coding = apps.get_model('archive', 'Coding')

    SYSTEMS_AND_CODES = [
        ('http://snomed.info/sct', [
            '201456002','268425006','39714003','1597004','302189007',
            '399198007','399173006','272479007','399348003','7771000','24028007',
            '69536005','609617007','731298009','729875002','1927002','71889004','210659002','210562007'
        ]),
        ('http://dicom.nema.org/resources/ontology/DCM', [
            'RG','SI','XC','M3D'
        ]),
    ]
    for system, codes in SYSTEMS_AND_CODES:
        Coding.objects.filter(system=system, code__in=codes).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('archive', '0003_initial_codings'),
    ]

    operations = [
        migrations.RunPython(init_codings, reverse_code=remove_codings),
        migrations.AlterField(
            model_name='imagingstudy',
            name='source_file',
            field=models.FileField(blank=True, help_text='Original uploaded file (PNG/STL)', null=True, upload_to=archive.models.imaging_study_upload_path),
        ),
    ]
