# Generated by Django 5.2.11 on 2026-03-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_device_serial_number_and_identifiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='procedure_occurrence_datetime',
        ),
    ]
