# Generated by Claude Code on 2026-01-27 18:36

from django.db import migrations


def create_initial_collection(apps, schema_editor):
    """Create the Bolton-Brush Growth Study Collection if it doesn't exist."""
    Collection = apps.get_model('archive', 'Collection')
    
    Collection.objects.get_or_create(
        short_name='BBGSC',
        defaults={
            'full_name': 'Bolton-Brush Growth Study Collection',
            'description': 'The Bolton-Brush Growth Study Collection',
            'institution': 'Case Western Reserve University',
        }
    )


def reverse_initial_collection(apps, schema_editor):
    """Remove the Bolton-Brush Growth Study Collection."""
    Collection = apps.get_model('archive', 'Collection')
    Collection.objects.filter(short_name='BBGSC').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_imagingstudy_source_file'),
    ]

    operations = [
        migrations.RunPython(create_initial_collection, reverse_initial_collection),
    ]
