# Generated by Django 4.2.25 on 2026-02-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_collection_address_alter_subject_address_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='imagingstudy',
            name='archive_ima_instanc_fd5557_idx',
        ),
        migrations.RenameField(
            model_name='imagingstudy',
            old_name='instance_uid',
            new_name='study_instance_uid',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='uid',
            new_name='series_instance_uid',
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='study_instance_uid',
            field=models.CharField(blank=True, help_text='DICOM StudyInstanceUID', max_length=64),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_instance_uid',
            field=models.CharField(blank=True, help_text='DICOM SeriesInstanceUID', max_length=64),
        ),
        migrations.AlterField(
            model_name='collection',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Address of the institution or physical location associated with this collection or its curator', null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.address'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='curator',
            field=models.CharField(blank=True, help_text='Primary curator or maintainer of the collection (an individual)', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date of the last record in this collection', null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='institution',
            field=models.CharField(blank=True, help_text='Institution responsible for the collection, associated with the curator', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date of the first record in this collection', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='sop_instance_uid',
            field=models.CharField(blank=True, help_text='DICOM SOPInstanceUID uniquely identifying this artifact instance', max_length=64),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['study_instance_uid'], name='archive_ima_study_i_8a5e48_idx'),
        ),
    ]
