# Generated by Django 5.2.11 on 2026-03-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_remove_procedure_occurrence_datetime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='physicalrecord',
            name='unique_physical_record_type_encounter',
        ),
        migrations.AddField(
            model_name='physicalrecord',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Free-text notes about this physical artifact'),
        ),
        migrations.AddField(
            model_name='subject',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Free-text notes about this subject (e.g. archival condition notes)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], help_text='Administrative gender for the subject. Values align with FHIR Patient.gender: https://hl7.org/fhir/patient-definitions.html#Patient.gender', max_length=16),
        ),
    ]
