# Generated by Django 5.2.11 on 2026-03-01 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_remove_imagingstudy_archive_ima_instanc_fd5557_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='endpoint',
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('off', 'off')], default='active', max_length=16)),
                ('connection_type', models.CharField(choices=[('dicom-stow-rs', 'dicom-stow-rs'), ('dicom-dimse', 'dicom-dimse'), ('smb', 'smb'), ('box', 'box'), ('drive', 'drive'), ('file', 'file'), ('other', 'other')], max_length=32)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('assigned_id', models.CharField(help_text='Endpoint-assigned identifier (UID, file id, path, etc.)', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('archived', 'archived'), ('failed', 'failed'), ('verified', 'verified')], default='pending', max_length=16)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(help_text='Record represented by this archived copy', on_delete=django.db.models.deletion.CASCADE, related_name='archive_locations', to='archive.record')),
                ('endpoint', models.ForeignKey(help_text='Archive endpoint where the record copy is stored', on_delete=django.db.models.deletion.PROTECT, related_name='archive_locations', to='archive.endpoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['status', 'connection_type'], name='archive_end_status_c47360_idx'),
        ),
        migrations.AddIndex(
            model_name='archivelocation',
            index=models.Index(fields=['record'], name='archive_arc_record__ea1688_idx'),
        ),
        migrations.AddIndex(
            model_name='archivelocation',
            index=models.Index(fields=['endpoint'], name='archive_arc_endpoin_4ce4be_idx'),
        ),
        migrations.AddIndex(
            model_name='archivelocation',
            index=models.Index(fields=['status'], name='archive_arc_status_e08656_idx'),
        ),
    ]
