# Generated by Django 5.2.11 on 2026-03-09 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_add_notes_fields_remove_physical_record_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalrecord',
            name='physical_location',
        ),
        migrations.RemoveField(
            model_name='physicalrecord',
            name='physical_location_box',
        ),
        migrations.RemoveField(
            model_name='physicalrecord',
            name='physical_location_compartment',
        ),
        migrations.RemoveField(
            model_name='physicalrecord',
            name='physical_location_shelf',
        ),
        migrations.RemoveField(
            model_name='physicalrecord',
            name='physical_location_tray',
        ),
        migrations.AddField(
            model_name='digitalrecord',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='One-based sequence within (encounter, record_type) among DigitalRecords. Auto-assigned on first save. Used in identifier_str suffix.', null=True),
        ),
        migrations.AddField(
            model_name='physicalrecord',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='One-based sequence within (encounter, record_type). Auto-assigned on first save. Used in identifier_str suffix.', null=True),
        ),
        migrations.CreateModel(
            name='PhysicalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('cabinet', models.CharField(blank=True, help_text='Cabinet or box number within the facility (e.g. "1", "10")', max_length=64)),
                ('shelf', models.CharField(blank=True, help_text='Shelf identifier within the cabinet (e.g. "A", "B")', max_length=64)),
                ('slot', models.CharField(blank=True, help_text='Slot or compartment identifier on the shelf (e.g. "16", "30")', max_length=64)),
                ('raw', models.CharField(blank=True, help_text='Original unparsed location string from the source spreadsheet', max_length=256)),
                ('address', models.ForeignKey(blank=True, help_text='Address of the building or facility where this storage slot is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_locations', to='archive.address')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cabinet', 'shelf', 'slot'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='physicalrecord',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Physical archive storage slots where this artifact is held', related_name='physical_records', to='archive.physicallocation'),
        ),
        migrations.AddIndex(
            model_name='physicallocation',
            index=models.Index(fields=['cabinet', 'shelf', 'slot'], name='archive_phy_cabinet_ebca88_idx'),
        ),
    ]
