# Generated by Django 4.2.25 on 2026-01-28 00:00

from django.db import migrations, models
import django.db.models.deletion


def copy_collection_to_subjects(apps, schema_editor):
    Subject = apps.get_model('archive', 'Subject')
    Record = apps.get_model('archive', 'Record')

    subjects_without_collection = Subject.objects.filter(collection__isnull=True)
    for subject in subjects_without_collection:
        collection_id = (
            Record.objects
            .filter(encounter__subject_id=subject.id)
            .exclude(collection__isnull=True)
            .order_by('pk')
            .values_list('collection_id', flat=True)
            .first()
        )
        if collection_id:
            subject.collection_id = collection_id
            subject.save(update_fields=['collection'])





class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_initial_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='archive.collection'),
        ),
        migrations.RunPython(copy_collection_to_subjects, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='record',
            name='collection',
        ),
    ]
