# Generated by OpenCode on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0010_seed_valuesets"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="actual_period_start_raw",
            field=models.CharField(
                blank=True,
                help_text="Original encounter date token from import sources",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="actual_period_start_precision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "Day"),
                    ("month", "Month"),
                    ("year", "Year"),
                    ("unknown", "Unknown"),
                ],
                help_text="Precision of actual_period_start",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="actual_period_start_uncertain",
            field=models.BooleanField(
                default=False,
                help_text="True when actual_period_start is inferred from partial data",
            ),
        ),
    ]
